### ISSUE TITLE
android bleManager.startPeripheralScan()

### ISSUE THREAD

**Issue by WangDan1989** [davejlin/flutter_ble_lib_ios_15#13]
E/flutter ( 6157): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: BleError (Error code: 600, ATT error code: null, iOS error code: null, Android error code: null, reason: Scan failed because application registration failed (code 6), internal message: null, device ID: null, service UUID: null, characteristic UUID: null, descriptor UUID: null)
E/flutter ( 6157): #0      ScanningMixin._scanEvents.<anonymous closure> (package:flutter_ble_lib_ios_15/src/bridge/scanning_mixin.dart:12:26)
E/flutter ( 6157): #1      Stream.handleError.<anonymous closure> (dart:async/stream.dart:923:16)
E/flutter ( 6157): #2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:269:17)
E/flutter ( 6157): #3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
E/flutter ( 6157): #4      _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
E/flutter ( 6157): #5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
E/flutter ( 6157): #6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
E/flutter ( 6157): #7      _DelayedError.perform (dart:async/stream_impl.dart:526:14)
E/flutter ( 6157): #8      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter ( 6157): #9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter ( 6157): #10     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 6157): #11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter ( 6157):

**Comment by Peterkrol12** [comment]
After a Google search, this problem seems to be related to an Android device running out of BLE resources. This could be due to some open connections on Peripherals or listeners on Characteristics. Make sure to close all connections and listeners when the application does not need them any longer.

It could also be caused by a 'busy' Bluetooth adapter, which could be caused by a number of things. Without more details, it is hard to determine the cause.

See the following StackOverflow post for more details into the issue:
https://stackoverflow.com/questions/39325864/android-ble-scan-failed-reason-app-registration-failed-for-uuid
